[project]
name = "mcp-on-cloudrun"
version = "0.1.0"
description = "Example of deploying a MCP server on Cloud Run"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp==2.6.1",
]
